In [1]:
import requests
import pandas as pd
import json


def fetch(url, params={}):
    response = requests.get(url,params)
    data = response.json()
    return data

def fetchAndDf(url, params={}):
    _data = fetch(url, params)
    _df = pd.DataFrame(_data['data'])
    _df.columns = _data['fields']
    return _df

# Exercises

In [2]:
data = fetch('https://ssd-api.jpl.nasa.gov/cad.api')

## Exercise 1

- How many objects are overall contained in the response?

In [3]:
len(data['data'])

64

- Store the actual data in a Pandas DataFrame. Each row should represent one object (e.g. asteroid or comet) and each column should represent one property of the object.

In [14]:
df = pd.DataFrame(data['data'], columns=data['fields'])
display(df.head(3))
df.shape

,des,orbit_id,jd,cd,dist,dist_min,dist_max,v_rel,v_inf,t_sigma_f,h
0,2024 TR4,1,2460590.546825580,2024-Oct-07 01:07,0.000747256650083642,0.00074690218162408,0.000747611108391375,15.0994699148702,14.8614477213719,< 00:01,26.87
1,671076,41,2460590.648020212,2024-Oct-07 03:33,0.0328084513324302,0.0328075647527531,0.0328093379567299,8.63908476048353,8.62967896840311,< 00:01,22.36
2,2024 SU3,7,2460590.649443006,2024-Oct-07 03:35,0.0144563165098256,0.014411605040263,0.0145010267351942,9.05011844729992,9.02972972901947,< 00:01,26.054

(64, 11)

- Which date range is covered?

```
from now to 60 days from now
```

- Only objects close to which planet(s) are returned?

```
Earth
```

- What are the objects minimum and maximum distances? And in which unit are distances measured?

```
there is no minimum distance
the maximum distance is 0.05 
the default unit is astronomical units (AU)
```

- How is the data sorted by default?

```
date
```

## Exercise 2

- How many objects will come close to the planet Mars between today and the end of 2024?

In [15]:
fetchAndDf('https://ssd-api.jpl.nasa.gov/cad.api', params={"body":"Earth", "date-max":"2024-12-31"})

,des,orbit_id,jd,cd,dist,dist_min,dist_max,v_rel,v_inf,t_sigma_f,h
0,2024 TR4,1,2460590.546825580,2024-Oct-07 01:07,0.000747256650083642,0.00074690218162408,0.000747611108391375,15.0994699148702,14.8614477213719,< 00:01,26.87
1,671076,41,2460590.648020212,2024-Oct-07 03:33,0.0328084513324302,0.0328075647527531,0.0328093379567299,8.63908476048353,8.62967896840311,< 00:01,22.36
2,2024 SU3,7,2460590.649443006,2024-Oct-07 03:35,0.0144563165098256,0.014411605040263,0.0145010267351942,9.05011844729992,9.02972972901947,< 00:01,26.054
3,2024 TY,4,2460590.704315506,2024-Oct-07 04:54,0.00451216140182462,0.00450122402443263,0.00452309851170152,15.2143530464319,15.1754906784653,< 00:01,26.159
4,2024 SF5,7,2460590.826847205,2024-Oct-07 07:51,0.0392025105481988,0.0391083152594775,0.0392967031778872,4.80292206496777,4.78874996681039,00:02,24.921
...,...,...,...,...,...,...,...,...,...,...,...
64,2018 XU3,11,2460655.851998684,2024-Dec-11 08:27,0.043064839317161,0.0430644438934215,0.0430652347428294,10.7810692467882,10.7753288313159,< 00:01,25.48
65,2007 XB23,8,2460656.255272166,2024-Dec-11 18:08,0.00297883841071384,0.000651049407590574,0.100601862015541,4.76594146748453,4.57441357832626,5_15:09,27.1
66,2022 YO1,2,2460662.153019928,2024-Dec-17 15:40,0.00505758338180306,3.63096523434893e-05,0.0134853830895743,14.3336018197223,14.2967997824337,15:24,30.01
67,2020 XY4,8,2460664.489565450,2024-Dec-19 23:45,0.0328107141872905,0.0293354802913488,0.0362906067599121,8.79010446124008,8.7808610762525,04:23,27.0
68,2017 YD2,2,2460672.417205282,2024-Dec-27 22:01,0.0461139822951646,0.0283217240754796,0.0639038233108139,9.90995073681323,9.90411848793791,00:16,28.7

- How many objects will be less or equal than 1 lunar distances away from the Earth until the end
of 2040?

In [6]:
fetchAndDf('https://ssd-api.jpl.nasa.gov/cad.api', params={"dist-max":"1LD","date-max":"2040-12-31"})

,des,orbit_id,jd,cd,dist,dist_min,dist_max,v_rel,v_inf,t_sigma_f,h
0,2024 TR4,1,2460590.546825580,2024-Oct-07 01:07,0.000747256650083642,0.00074690218162408,0.000747611108391375,15.0994699148702,14.8614477213719,< 00:01,26.87
1,2024 TW2,2,2460590.968345753,2024-Oct-07 11:14,0.00192407259871393,0.00191930533341702,0.00192883967613553,16.9355747332767,16.8536069436648,< 00:01,28.628
2,2013 GM3,19,2461145.177383204,2026-Apr-14 16:15,0.0017415225166616,5.20926933265413e-05,0.00752815062677095,7.40950828593481,7.20006045734385,07:56,26.3
3,2021 EO2,11,2461910.728367637,2028-May-19 05:29,0.00250374279906793,0.00102681982381983,0.00853793900153388,6.09763813539855,5.9205399943503,2_06:17,27.87
4,153814,187,2461948.724523629,2028-Jun-26 05:23,0.00166253927892303,0.00166237956640619,0.00166269899181251,10.2426018177876,10.0849183958214,< 00:01,18.29
5,99942,218,2462240.407091947,2029-Apr-13 21:46,0.000254091206489515,0.000254068489663706,0.000254113923490783,7.42253730175426,5.84135588627817,< 00:01,19.09
6,2001 AV43,43,2462452.141957826,2029-Nov-11 15:24,0.00209265968977497,0.00209119456873008,0.00209412605822264,3.99790510260908,3.66561657003811,00:03,24.6
7,2019 EH1,2,2463292.474408685,2032-Feb-29 23:23,0.00229235179467739,0.000118576657964578,0.154258708706973,14.6226965272265,14.5429909212602,9_08:58,30.12
8,2008 DB,25,2463459.118558205,2032-Aug-14 14:51,0.000851852145945288,0.000843176632483197,0.000861096118179401,7.39467602697345,6.95884341003796,00:02,25.8
9,2022 MK1,15,2464163.686152576,2034-Jul-20 04:28,0.00241709489986423,0.00224836123173409,0.00276982185390669,6.62811070418486,6.45965601484246,15:25,24.02
10,2022 SX55,1,2464588.329571312,2035-Sep-17 19:55,0.00216548085165508,7.36334670740316e-06,0.035199182469001,12.197005668037,12.0957050661336,03:29,30.19
11,2017 FU102,7,2464786.479788331,2036-Apr-02 23:31,0.000862716175775921,0.000667456296990492,0.00444714991405414,7.65307218146634,7.23827045535342,14:22,28.7
12,2023 EB,11,2464988.043259949,2036-Oct-21 13:02,0.00114947288990452,0.00110107370677759,0.0117133027088399,7.71187764839918,7.4052045759684,1_09:21,26.20

- Query objects classified as PHA (Potentially Hazardous Asteroids) in the next five years, sort the
objects according to their distances, and limit the results to the first 10 objects. Additionally,
query also the objects’ diameter, which the API does not return by default. Then store the data
in a Pandas DataFrame.

 Note: Sort and limit the data directly in the API request.

In [7]:
fetchAndDf('https://ssd-api.jpl.nasa.gov/cad.api', params={"pha":True,"date-max":f"+{365*5}","sort":"dist","limit":10,"diameter":True})

,des,orbit_id,jd,cd,dist,dist_min,dist_max,v_rel,v_inf,t_sigma_f,h,diameter,diameter_sigma
0,99942,218,2462240.407091947,2029-Apr-13 21:46,0.000254091206489515,0.000254068489663706,0.000254113923490783,7.42253730175426,5.84135588627817,< 00:01,19.09,0.34,0.04
1,153814,187,2461948.724523629,2028-Jun-26 05:23,0.00166253927892303,0.00166237956640619,0.00166269899181251,10.2426018177876,10.0849183958214,< 00:01,18.29,0.932,0.011
2,137108,100,2461624.799043508,2027-Aug-07 07:11,0.0026060207695371,0.00260524407264729,0.00260679746682733,26.2840539548859,26.245125796325,< 00:01,18.05,None,None
3,35396,393,2462070.780248924,2028-Oct-26 06:44,0.00621150282058691,0.00621136780772082,0.00621163783345618,13.9196802583589,13.8888293502523,< 00:01,17.01,0.704,0.103
4,292220,111,2462164.683038880,2029-Jan-28 04:24,0.00819149268848162,0.00819117140282567,0.00819181397418554,4.90382466551491,4.8370392196345,< 00:01,19.39,None,None
5,2011 LJ19,52,2461978.268638406,2028-Jul-25 18:27,0.00850325102468403,0.00184618067572534,0.0168862769439671,9.80196702325942,9.76994682201792,2_22:27,21.3,None,None
6,2023 GQ2,6,2462092.065383919,2028-Nov-16 13:34,0.0101544500776024,0.0101013238697878,0.0102075765005221,21.460287928239,21.4480574292464,00:04,19.86,None,None
7,2000 SL10,13,2462270.456197673,2029-May-13 22:57,0.0119335641030772,0.0109339153306716,0.0427929373164914,8.49171104168455,8.46537679421759,4_19:47,22.16,None,None
8,2018 GG2,18,2461865.423933289,2028-Apr-03 22:10,0.0147407148799979,0.0147378892624163,0.0147435405131396,29.4775539223128,29.471421281245,< 00:01,19.26,None,None
9,2020 XR,33,2460648.727125295,2024-Dec-04 05:27,0.0147682677317004,0.0147675726711905,0.0147689627939077,12.3095802274376,12.2949146778919,< 00:01,19.9,None,None

## Exercise 3

-  Query the API for all potentially hazardous objects in the next 50 years.

-  Store the response (not only the data, but the entire object) in a JSON file.

-  Read in the data from the JSON file into a Python object (list of dictionaries)

In [8]:
res = fetch('https://ssd-api.jpl.nasa.gov/cad.api', params={"pha":True,"date-max":f"+{365*50}"})

In [9]:
with open('results/excercise3.json', 'w+') as f:
    json.dump(res,f)

In [10]:
with open('results/excercise3.json', 'r') as f:
    df = json.load(f)

In [11]:
df == res

True